# -*- coding:utf-8 -*-

__author__      = "Leidinice Silva"
__email__       = "leidinicesilva@gmail.com"
__date__        = "09/19/2022"
__description__ = "Dictionary of the inmet automatic station"

"""
Dictionaries of the station

> {station}

    Stations name:

    where:

        1 - automatic station name.

    Examples:

         1: Santa_vitoria_do_palmar'
         2: jaguarao'

"""

names = {1	 :['SANTA_VITORIA_DO_PALMAR',  	          'SANTA VITÓRIA DO PALMAR'],
		 2 	 :['JAGUARAO',                            'JAGUARÃO'],
		 3 	 :['RIO_GRANDE',                          'RIO GRANDE'],
		 4	 :['CAPAO_DO_LEAO',                       'CAPÃO DO LEÃO'],
		 5	 :['CANGUCU',                             'CANGUÇU'],
		 6	 :['BAGE',                                'BAGÉ'],
		 7	 :['MOSTARDAS',                           'MOSTARDAS'],
		 8	 :['DOM_PEDRITO',                         'DOM PEDRITO'],
		 9	 :['SANTANA_DO_LIVRAMENTO',               'SANTANA DO LIVRAMENTO'],
		 10	 :['CAMAQUA',                             'CAMAQUÃ'],
		 11	 :['CACAPAVA_DO_SUL',                     'CAÇAPAVA DO SUL'],
		 12	 :['ENCRUZILHADA_DO_SUL',                 'ENCRUZILHADA DO SUL'],
		 13	 :['QUARAI',                              'QUARAÍ'],
		 14	 :['SAO_GABRIEL',                         'SÃO GABRIEL'],
		 15	 :['PORTO_ALEGRE',                        'PORTO ALEGRE'],
		 16	 :['TRAMANDAI',                           'TRAMANDAÍ'],
		 17	 :['TUPANCIRETA',                         'TUPANCIRETÃ'],
		 18	 :['RIO_PARDO',                           'RIO PARDO'],
		 19	 :['URUGUAIANA',                          'URUGUAIANA'],
		 20	 :['ALEGRETE',                            'ALEGRETE'],
		 21	 :['SANTA_MARIA',                         'SANTA MARIA'],
		 22	 :['SAO_VICENTE_DO_SUL',                  'SÃO VICENTE DO SUL'],
		 23	 :['CAMPO_BOM',                           'CAMPO BOM'],
		 24  :['TEUTONIA',                            'TEUTONIA'],
		 25	 :['CANELA',                              'CANELA'],
		 26	 :['TORRES',                              'TORRES'],
		 27	 :['SANTIAGO',                            'SANTIAGO'],
		 28	 :['BENTO_GONCALVES',                     'BENTO GONÇALVES'],
		 29	 :['CAMBARA_DO_SUL',                      'CAMBARA DO SUL'],
		 30	 :['ARARANGUA',                           'ARARANGUA'],
		 31	 :['SOLEDADE',                            'SOLEDADE'],
		 32	 :['SAO_JOSE_DOS_AUSENTES',               'SÃO JOSÉ DOS AUSENTES'],
		 33	 :['SERAFINA_CORREA',                     'SERAFINA CORRÊA'],
		 34	 :['IBIRUBA',                             'IBIRUBA'],
		 35	 :['SAO BORJA',                           'SÃO BORJA'],
		 36	 :['LAGUNA_FAROL_DE_SANTA_MARTA',         'LAGUNA - FAROL DE SANTA MARTA'],
		 37	 :['CRUZ_ALTA',                           'CRUZ ALTA'],
		 38	 :['URUSSANGA',           		          'URUSSANGA'],
		 39	 :['VACARIA',                 		      'VACARIA'],
		 40	 :['SAO_LUIZ_GONZAGA',	     		      'SÃO LUIZ GONZAGA'],
		 41	 :['SAO_JOAQUIM',    		              'SÃO JOAQUIM'],
		 42	 :['PASSO_FUNDO',                         'PASSO FUNDO'],
		 43	 :['LAGOA_VERMELHA',                      'LAGOA VERMELHA'],
		 44	 :['BOM_JARDIM_DA_SERRA_MORRO_DA_IGREJA', 'BOM JARDIM DA SERRA - MORRO DA IGREJA'],
		 45	 :['CHAPECO',	                          'CHAPECÓ'],
		 46	 :['PALMEIRA_DAS_MISSOES',                'PALMEIRA DAS MISSÕES'],
		 47  :['SANTA_ROSA',	                      'SANTA ROSA'],
		 48	 :['SANTO_AUGUSTO',	                      'SANTO AUGUSTO'],
		 49	 :['LAGES',	                              'LAGES'],
		 50	 :['RANCHO_QUEIMADO',	                  'RANCHO QUEIMADO'],
		 51	 :['ERECHIM',	                          'ERECHIM'],
		 52	 :['FLORIANOPOLIS',	                      'FLORIANÓPOLIS'],
		 53	 :['ITUPORANGA',                          'ITUPORANGA'],
		 54	 :['FREDERICO_WESTPHALEN',                'FREDERICO WESTPHALEN'],
		 55	 :['CAMPOS_NOVOS',                        'CAMPOS NOVOS'],
		 56	 :['CURITIBANOS',                         'CURITIBANOS'],
		 57	 :['JOACABA',                             'JOACABA'],
		 58	 :['ITAJAI',                              'ITAJAÍ'],
		 59	 :['XANXERE',                             'XANXERE'],
		 60	 :['RIO_DO_CAMPO',                        'RIO DO CAMPO'],
		 61	 :['INDAIAL',	                          'INDAIAL'],
		 62	 :['CACADOR',	                          'CAÇADOR'],
		 63	 :['SAO_MIGUEL_DO_OESTE',           	  'SAO MIGUEL DO OESTE'],
		 64	 :['CLEVELANDIA',	                      'CLEVELANDIA'],
		 65	 :['NOVO_HORIZONTE',	                  'NOVO HORIZONTE'],
		 66	 :['GENERAL_CARNEIRO',  	              'GENERAL CARNEIRO'],
		 67	 :['MAJOR_VIEIRA',	                      'MAJOR VIEIRA'],
		 68	 :['DIONISIO_CERQUEIRA',	              'DIONÍSIO CERQUEIRA'],
		 69	 :['RIO_NEGRINHO',	                      'RIO NEGRINHO'],
		 70	 :['ITAPOA',                              'ITAPOA'],
		 71	 :['SAO_MATEUS_DO_SUL',	                  'SÃO MATEUS DO SUL'],
		 72	 :['PLANALTO',	                          'PLANALTO'],
		 73	 :['DOIS_VIZINHOS',	                      'DOIS VIZINHOS'],
		 74	 :['FOZ_DO_IGUACU',	                      'FOZ DO IGUAÇU'],
		 75	 :['INACIO_MARTINS',                      'INÁCIO MARTINS'],
		 76	 :['MORRETES',                            'MORRETES'],
		 77	 :['ILHA_DO_MEL',                         'ILHA DO MEL'],
		 78	 :['CURITIBA',                            'CURITIBA'],
		 79	 :['LARANJEIRAS_DO_SUL',                  'LARANJEIRAS DO SUL'],
		 80	 :['COLOMBO',                             'COLOMBO'],
		 81	 :['IVAI',	                              'IVAI'],
		 82	 :['BARRA_DO_TURVO',	                  'BARRA DO TURVO'],
		 83	 :['CASTRO',                              'CASTRO'],
		 84	 :['IGUAPE',                              'IGUAPE'],
		 85	 :['CAMPINA_DA_LAGOA',                    'CAMPINA DA LAGOA'],
		 86	 :['MAL_CANDIDO_RONDON',	              'MAL. CÂNDIDO RONDON'],
		 87	 :['REGISTRO',	                          'REGISTRO'],
		 88	 :['NOVA_TEBAS',	                      'NOVA TEBAS'],
		 89	 :['VENTANIA',	                          'VENTANIA'],
		 90	 :['GOIOERE',	                          'GOIOERE'],
		 91	 :['ITAPEVA',	                          'ITAPEVA'],
		 92	 :['SETE_QUEDAS',	                      'SETE QUEDAS'],
		 93	 :['BRAGANCA_PAULISTA',	                  'BRAGANCA PAULISTA'],
		 94	 :['SAO_MIGUEL_ARCANJO',	              'SÃO MIGUEL ARCANJO'],
		 95	 :['BERTIOGA',                            'BERTIOGA'],
		 96	 :['SAO_SEBASTIAO',	                      'SÃO SEBASTIAO'],
		 97	 :['JAPIRA',                              'JAPIRA'],
		 98	 :['SAO_PAULO_INTERLAGOS',                'SÃO PAULO INTERLAGOS'],
		 99	 :['IGUATEMI',	                          'IGUATEMI'],
		 100 :['BARUERI',	                          'BARUERI'],
		 101 :['JOAQUIM_TAVORA',                      'JOAQUIM TÁVORA'],
		 102 :['SAO_PAULO_MIRANTE',	                  'SÃO PAULO - MIRANTE'],
		 103 :['ITAQUIRAI',	                          'ITAQUIRAI'],
		 104 :['MARINGA',	                          'MARINGA'],
		 105 :['NOVA_FATIMA', 	                      'NOVA FÁTIMA'],
		 106 :['ICARAIMA',	                          'ICARAIMA'],
		 107 :['CIDADE_GAUCHA',	                      'CIDADE GAUCHA'],
		 108 :['SOROCABA',	                          'SOROCABA'],
		 109 :['SAO_LUIS_DO_PARAITINGA',              'SÃO LUIS DO PARAITINGA'],
		 110 :['PARATI',	                          'PARATI'],
		 111 :['AVARE',	                              'AVARE'],
		 112 :['MARAMBAIA',	                          'MARAMBAIA'],
		 113 :['TAUBATE',                             'TAUBATE'],
		 114 :['AMAMBAI',                             'AMAMBAI'],
		 115 :['FORTE_DE_COPACABANA',                 'FORTE DE COPACABANA'],
		 116 :['ARRAIAL_DO_CABO',                     'ARRAIAL DO CABO'],
		 117 :['ANGRA_DOS_REIS',                      'ANGRA DOS REIS'],
		 118 :['ARAL_MOREIRA',                        'ARAL MOREIRA'],
		 119 :['OURINHOS',                            'OURINHOS'],
		 120 :['RIO_DE_JANEIRO_JACAREPAGUA',          'RIO DE JANEIRO - JACAREPAGUA'],
		 121 :['SAQUAREMA',	                          'SAQUAREMA'],
		 122 :['NITEROI',	                          'NITEROI'],
		 123 :['MONTE_VERDE',	                      'MONTE VERDE'],
		 124 :['VILA_MILITAR',	                      'VILA MILITAR'],
		 125 :['JUTI',	                              'JUTI'],
		 126 :['ECOLOGIA_AGRICOLA',	                  'ECOLOGIA AGRICOLA'],
		 127 :['CAMPOS_DO_JORDAO',	                  'CAMPOS DO JORDÃO'],
		 128 :['PIRACICABA',	                      'PIRACICABA'],
		 129 :['CACHOEIRA_PAULISTA',	              'CACHOEIRA PAULISTA'],
		 130 :['CAARAPO',	                          'CAARAPO'],
		 131 :['RIO_CLARO',	                          'RIO CLARO'],
		 132 :['SILVA_JARDIM',	                      'SILVA JARDIM'],
		 133 :['DIAMANTE_DO_NORTE',	                  'DIAMANTE DO NORTE'],
		 134 :['XEREM',	                              'XEREM'],
		 135 :['LAGUNA_CARAPA',	                      'LAGUNA CARAPA'],
		 136 :['PONTA_PORA',	                      'PONTA PORÃ'],
		 137 :['PARANAPOEMA',	                      'PARANAPOEMA'],
		 138 :['PICO_DO_COUTO',	                      'PICO DO COUTO'],
		 139 :['RESENDE',	                          'RESENDE'],
		 140 :['TERESOPOLIS',	                      'TERESOPOLIS'],
		 141 :['ITAPIRA',	                          'ITAPIRA'],
		 142 :['PASSA_QUATRO',	                      'PASSA QUATRO'],
		 143 :['MACAE',                               'MACAÉ'],
		 144 :['ITATIAIA',	                          'ITATIAIA'],
		 145 :['RANCHARIA',	                          'RANCHARIA'],
		 146 :['BARRA_BONITA',                        'BARRA BONITA'],
		 147 :['BAURU',	                              'BAURU'],
		 148 :['VALENCA',	                          'VALENCA'],
		 149 :['NOVA_FRIBURGO',	                      'NOVA FRIBURGO'],
		 150 :['MARIA_DA_FE',                         'MARIA DA FÉ'],
		 151 :['FATIMA_DO_SUL',	                      'FÁTIMA DO SUL'],
		 152 :['IVINHEMA',	                          'IVINHEMA'],
		 153 :['MARILIA',	                          'MARILIA'],
		 154 :['DOURADOS',	                          'DOURADOS'],
		 155 :['ANGELICA',	                          'ANGELICA'],
		 156 :['PRESIDENTE_PRUDENTE',	              'PRESIDENTE PRUDENTE'],
		 157 :['BELA_VISTA',                          'BELA VISTA'],
		 158 :['TRES_RIOS',	                          'TRÊS RIOS'],
		 159 :['ITAPORA',                             'ITAPORA'],
		 160 :['NOVA_ANDRADINA'	,                     'NOVA ANDRADINA'],
		 161 :['SAO_TOME',                            'SÃO TOME'],
		 162 :['SAO_CARLOS',                          'SÃO CARLOS'],
		 163 :['SANTA_MARIA_MADALENA',                'SANTA MARIA MADALENA'],
		 164 :['CARMO',	                              'CARMO'],
		 165 :['TUPA',	                              'TUPA'],
		 166 :['CALDAS',	                          'CALDAS'],
		 167 :['IBITINGA',                            'IBITINGA'],
		 168 :['CASA_BRANCA', 	                      'CASA BRANCA'],
		 169 :['RIO_BRILHANTE',	                      'RIO BRILHANTE'],
		 170 :['JUIZ_DE_FORA',	                      'JUIZ DE FORA'],
		 171 :['BATAGUASSU',                          'BATAGUASSU'],
		 172 :['CAMPOS',                              'CAMPOS'],
		 173 :['PORTO_MURTINHO',                      'PORTO MURTINHO'],
		 174 :['MACHADO',                             'MACHADO'],
		 175 :['LINS',                                'LINS'],
		 176 :['MARACAJU',                            'MARACAJU'],
		 177 :['CAMBUCI',                             'CAMBUCI'],
		 178 :['VARGINHA',                            'VARGINHA'],
		 179 :['CORONEL_PACHECO',	                  'CORONEL PACHECO'],
		 180 :['JARDIM',                              'JARDIM'],
		 181 :['SAO_SIMAO',	                          'SÃO SIMAO'],
		 182 :['DRACENA',	                          'DRACENA'],
		 183 :['NOVA_ALVORADA_DO_SUL',	              'NOVA ALVORADA DO SUL'],
		 184 :['PRADOPOLIS',	                      'PRADOPOLIS'],
		 185 :['VALPARAISO',	                      'VALPARAISO'],
		 186 :['SANTA_RITA_DO_PARDO',	              'SANTA RITA DO PARDO'],
		 187 :['BRASILANDIA',                         'BRASILÂNDIA'],
		 188 :['BONITO',	                          'BONITO'],
		 189 :['BARBACENA',	                          'BARBACENA'],
		 190 :['SAO_JOAO DEL REI',	                  'SÃO JOAO DEL REI'],
		 191 :['ARIRANHA',	                          'ARIRANHA'],
		 192 :['MURIAE',	                          'MURIAE'],
		 193 :['PRES_KENNEDY'	,	                  'PRES. KENNEDY'],
		 194 :['JOSE_BONIFACIO',                      'JOSE BONIFACIO'],
		 195 :['SIDROLANDIA',                         'SIDROLANDIA'],
		 196 :['BEBDOURO',                            'BEBDOURO'],
		 197 :['SAO_SEBASTIAO_DO_PARAISO',            'SÃO SEBASTIÃO DO PARAÍSO'],
		 198 :['TRES_LAGOAS',	                      'TRÊS LAGOAS'],
		 199 :['VICOSA'	,	                          'VIÇOSA'],
		 200 :['ALEGRE'	,	                          'ALEGRE'],
		 201 :['PASSOS',	                          'PASSOS'],
		 202 :['OLIVEIRA',	                          'OLIVEIRA'],
		 203 :['ALFREDO_CHAVES',	                  'ALFREDO CHAVES'],
		 204 :['FRANCA', 	                          'FRANCA'],
		 205 :['BARRETOS',	                          'BARRETOS'],
		 206 :['OURO_BRANCO',                         'OURO BRANCO'],
		 207 :['AQUIDAUANA',	                      'AQUIDAUANA'],
		 208 :['VILA_VELHA',	                      'VILA VELHA'],
		 209 :['RIBAS_DO_RIO_PARDO',                  'RIBAS DO RIO PARDO'],
		 210 :['FORMIGA',	                          'FORMIGA'],
		 211 :['CAMPO_GRANDE', 	                      'CAMPO GRANDE'],
		 212 :['AGUA_CLARA'	,	                      'ÁGUA CLARA'],
		 213 :['VOTUPORANGA',	                      'VOTUPORANGA'],
		 214 :['MIRANDA',	                          'MIRANDA'],
		 215 :['ITUVERAVA',	                          'ITUVERAVA'],
		 216 :['SELVIRIA',	                          'SELVIRIA'],
		 217 :['VITORIA',	                          'VITÓRIA'],
		 218 :['MANHUACU',	                          'MANHUACU'],
		 219 :['VENDA_NOVA_DO_IMIGRANTE',             'VENDA NOVA DO IMIGRANTE'],
		 220 :['DIVINOPOLIS',	                      'DIVINOPOLIS'],
		 221 :['JALES',	                              'JALES'],
		 222 :['AFONSO_CLAUDIO'	,	                  'AFONSO CLAUDIO'],
		 223 :['IBIRITE_ROLA_MOCA',                   'IBIRITE (ROLA MOCA)'],
		 224 :['BAMBUI',	                          'BAMBUI'],
		 225 :['SANTA_TERESA',	                      'SANTA TERESA'],
		 226 :['CONCEICAO_DAS_ALAGOAS',	              'CONCEICAO DAS ALAGOAS'],
		 227 :['BELO_HORIZONTE_CERCADINHO',           'BELO HORIZONTE - CERCADINHO'],
		 228 :['BANDEIRANTES',	                      'BANDEIRANTES'],
		 229 :['FLORESTAL',	                          'FLORESTAL'],
		 230 :['PAMPULHA',	                          'PAMPULHA'],
		 231 :['SACRAMENTO',	                      'SACRAMENTO'],
		 232 :['CARATINGA',	                          'CARATINGA'],
		 233 :['UBERABA',	                          'UBERABA'],
		 234 :['PARANAIBA',	                          'PARANAIBA'],
		 235 :['ARAXA',	                              'ARAXA'],
		 236 :['CAMAPUA',                             'CAMAPUA'],
		 237 :['TIMOTEO',	                          'TIMÓTEO'],
		 238 :['CAMPINA_VERDE',	                      'CAMPINA VERDE'],
		 239 :['AIMORES',                             'AIMORES'],
		 240 :['DORES_DO_INDAIA',	                  'DORES DO INDAIA'],
		 241 :['SETE_LAGOAS',	                      'SETE LAGOAS'],
		 242 :['SAO_GABRIEL_DO_OESTE',                'SAO GABRIEL DO OESTE'],
		 243 :['MARILANDIA',	                      'MARILANDIA'],
		 244 :['LINHARES',	                          'LINHARES'],
		 245 :['POMPEU',	                          'POMPEU'],
		 246 :['CASSILANDIA',	                      'CASSILANDIA'],
		 247 :['CORUMBA',	                          'CORUMBA'],
		 248 :['PATROCINIO',	                      'PATROCINIO'],
		 249 :['NHUMIRIM',	                          'NHUMIRIM'],
		 250 :['SAO_SIMAO',	                          'SÃO SIMAO'],
		 251 :['ITUIUTABA',	                          'ITUIUTABA'],
		 252 :['UBERLANDIA',	                      'UBERLÂNDIA'],
		 253 :['GOVERNADOR_VALADARES',                'GOVERNADOR VALADARES'],
		 254 :['COSTA_RICA',	                      'COSTA RICA'],
		 255 :['CHAPADAO_DO_SUL',	                  'CHAPADÃO DO SUL'],
		 256 :['GUANHAES',	                          'GUANHAES'],
		 257 :['MANTENA',	                          'MANTENA'],
		 258 :['CURVELO',	                          'CURVELO'],
		 259 :['SAO_MATEUS',	                      'SÃO MATEUS'],
		 260 :['NOVA_VENECIA',	                      'NOVA VENECIA'],
		 261 :['PATOS_DE_MINAS',	                  'PATOS DE MINAS'],
		 262 :['COXIM',	                              'COXIM'],
		 263 :['ITUMBIARA',	                          'ITUMBIARA'],
		 264 :['ECOPORANGA',	                      'ECOPORANGA'],
		 265 :['DIAMANTINA',	                      'DIAMANTINA'],
		 266 :['TRES_MARIAS',                         'TRÊS MARIAS'],
		 267 :['CATALAO',                             'CATALÃO'],
		 268 :['PEDRO_GOMES',                         'PEDRO GOMES'],
		 269 :['ABROLHOS',                            'ABROLHOS'],
		 270 :['JATAI',                               'JATAI'],
		 271 :['TEOFILO_OTONI',	                      'TEÓFILO OTONI'],
		 272 :['SONORA',                              'SONORA'],
		 273 :['ALTO_TAQUARI',                        'ALTO TAQUARI'],
		 274 :['SERRA_DOS_AIMORES',	                  'SERRA DOS AIMORES'],
		 275 :['RIO_VERDE',	                          'RIO VERDE'],
		 276 :['JOAO_PINHEIRO',	                      'JOÃO PINHEIRO'],
		 277 :['CARAVELAS',	                          'CARAVELAS'],
		 278 :['MORRINHOS',	                          'MORRINHOS'],
		 279 :['CAPELINHA',	                          'CAPELINHA'],
		 280 :['GUARDA_MOR',	                      'GUARDA-MOR'],
		 281 :['MINEIROS',	                          'MINEIROS'],
		 282 :['ALTO_ARAGUAIA',	                      'ALTO ARAGUAIA'],
		 283 :['EDEIA',                               'EDEIA'],
		 284 :['PIRES_DO_RIO',                        'PIRES DO RIO'],
		 285 :['ITIQUIRA',	                          'ITIQUIRA'],
		 286 :['PIRAPORA',	                          'PIRAPORA'],
		 287 :['PARACATU',	                          'PARACATU'],
		 288 :['ITAMARAJU',                           'ITAMARAJU']}
